name: Dart code checker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, v* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.19.1
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17.x'
      - run: flutter pub get
      - run: flutter --version
      - name: dart add test in dev_dependencies
        run: dart pub add --dev test
      - name: Install Dart dependencies
        run: dart pub get
      - name: Flutter analyze
        run: flutter analyze
      - name: Dart Analyze project for fatal
        run: dart analyze --fatal-warnings --fatal-infos .
      - name: Verify formatting
        run: dart format --set-exit-if-changed .
      - name: Check /lib via Dart Code Metrics
        uses: dart-code-checker/dart-code-metrics-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folders: "lib"
          pull_request_comment: true
          fatal_warnings: true
          fatal_performance: true
          fatal_style: true
          check_unused_files: true
          check_unused_files_folders: "lib"
      - name: Check Flutter build APK
        run: flutter build apk
